version: '3.3'

services:

  traefik:
    image: traefik:1.7-alpine
    networks:
      - traefik_public
    volumes:
      - acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # traefik dashboard
    command:
      # Use your favourite settings here, but add:
      - --docker
      - --docker.swarmMode
      - --docker.domain=traefik
      - --docker.watch
      - --api
      - --defaultentrypoints=http,https
      - --acme
      - --acme.email=max@domain.com
        # TODO: envvar for email and default domain
      - --acme.httpchallenge
      - --acme.httpchallenge.entrypoint=http
      - --acme.onhostrule=true
      - --acme.entrypoint=https
      - --entryPoints=Name:https Address::443 TLS
      - --entryPoints=Name:http Address::80
      - --acme.storage=/etc/traefik/acme/acme.json
      - --acme.acmelogging
      - --acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --acme.caserver=https://acme-v02.api.letsencrypt.org/directory
    logging:
      options:
        max-size: "500k"


volumes:
  acme:

networks:
  traefik_public:
    external: true